### ISSUE TITLE
SL_PREFETCHSTATUS_UNDERFLOW after playing sounds

### ISSUE THREAD

**Issue by AhmedX6** [termux/play-audio#10] opened 2018-06-07 09:46 UTC
Hello,

I integrated this code on my project and I'm playing some sounds depending on events.
I added a threadpool implementation to make the song playing asynchronous.
It works, but after some sound plays I get` "play-audio: underflow when prefetching data"` from the `opensl_prefetch_callback(SLPrefetchStatusItf caller, void *pContext, SLuint32 event)` callback ?
Please can you explain me what does that mean ?

**Comment by ghost** [comment] 2019-01-15 11:48
Duplicate of https://github.com/termux/play-audio/issues/4.

**Closed as completed by ghost** 2019-01-15 11:48 UTC
Labels: duplicate
